In [31]:
from mxnet import nd
a = nd.arange(9)
print(a)
print(a.shape)
print(a.size)
b = a.reshape([3, 3])
print('a is', a)
print('b is', b)


[0. 1. 2. 3. 4. 5. 6. 7. 8.]
<NDArray 9 @cpu(0)>
(9,)
9
a is 
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
<NDArray 9 @cpu(0)>
b is 
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)>


In [25]:
c = nd.zeros((4,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 4x4 @cpu(0)>

In [26]:
d = nd.ones((5, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 5x4 @cpu(0)>

In [73]:
A = nd.array([[1,2,3], [3,4,5],[7,2,8], [2,2,4]])
print(A)
print(A.shape)


[[1. 2. 3.]
 [3. 4. 5.]
 [7. 2. 8.]
 [2. 2. 4.]]
<NDArray 4x3 @cpu(0)>
(4, 3)


In [75]:
C = nd.array([[1,3,5], [2,3,3], [5,3,5], [2,3,2], [2,1,1]])
# print(C.shape)
print(C.T.shape)
print(C.T)

(3, 5)

[[1. 2. 5. 2. 2.]
 [3. 3. 3. 3. 1.]
 [5. 3. 5. 2. 1.]]
<NDArray 3x5 @cpu(0)>


In [77]:
B = nd.random.normal(0, 10, shape=[4, 3])
print(B)
print(B.shape)


[[ -7.9218464   9.321043  -31.557741 ]
 [ 21.935299   -5.385921   -8.611334 ]
 [-18.815191   -7.2057076  -3.5601573]
 [ -1.5963985  17.974476    1.9594946]]
<NDArray 4x3 @cpu(0)>
(4, 3)


In [47]:
A.exp()


[[2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [2.0085537e+01 5.4598148e+01 1.4841316e+02]
 [1.0966332e+03 7.3890562e+00 2.9809580e+03]
 [7.3890562e+00 7.3890562e+00 5.4598148e+01]]
<NDArray 4x3 @cpu(0)>

### 注意
点积运算第一个矩阵的列数（第1维）必须和第二个矩阵的行数(第 0 维度) 相同

In [71]:
D = nd.dot(A, C.T)
print(D)
print(D.shape)


[[22. 17. 26. 14.  7.]
 [40. 33. 52. 28. 15.]
 [53. 44. 81. 36. 24.]
 [28. 22. 36. 18. 10.]]
<NDArray 4x5 @cpu(0)>
(4, 5)


In [79]:
nd.concat(A, B, dim=0)
nd.concat(A, B, dim=1)


[[  1.          2.          3.         -7.9218464   9.321043  -31.557741 ]
 [  3.          4.          5.         21.935299   -5.385921   -8.611334 ]
 [  7.          2.          8.        -18.815191   -7.2057076  -3.5601573]
 [  2.          2.          4.         -1.5963985  17.974476    1.9594946]]
<NDArray 4x6 @cpu(0)>

In [80]:
A == B


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<NDArray 4x3 @cpu(0)>

In [90]:
nd.array([[1,0],[0,1], [1, 0]]).norm()


[1.7320508]
<NDArray 1 @cpu(0)>

In [84]:
A.norm()


[14.3178215]
<NDArray 1 @cpu(0)>

In [92]:
print(A)
A[0:1]


[[1. 2. 3.]
 [3. 4. 5.]
 [7. 2. 8.]
 [2. 2. 4.]]
<NDArray 4x3 @cpu(0)>



[[1. 2. 3.]]
<NDArray 1x3 @cpu(0)>

In [94]:
A[1: 2, :] = 12
A


[[ 1.  2.  3.]
 [12. 12. 12.]
 [ 7.  2.  8.]
 [ 2.  2.  4.]]
<NDArray 4x3 @cpu(0)>